### PR TITLE
Simplified delegate methods

### PR DESCRIPTION
**Pull request by dimazen**
Replace 4 didSwipeView(Up | Down | Left | Right) methods with single swipeableView: didSwipeView:inDirection:

### CODE REVIEW

**Comment by dimazen** [comment]
Is there any way to re-run CI, because I can build it easily?

**Comment by zhxnlai** [comment]
Thanks, I think your code looks good! Don't worry about the CI because there was an error in the travis.yml causing the failure.

Would you mind updating the sample app as well?

**Comment by dimazen** [comment]
@zhxnlai Tomorrow will be done :)

**Comment by dimazen** [comment]
@zhxnlai done.

**Comment by zhxnlai** [comment]
Thanks! @dimazen

**Pull request closed without merging**
